In [1]:
import numpy as np

In [3]:
data = np.array([[2,2], [3,4], [5,6]])

In [4]:
type(data)

numpy.ndarray

In [5]:
# Number of dimensions (axes).
data.ndim

2

In [6]:
# A tuple that contains the number of elements (i.e., the length) for each dimension (axis) of the array.
data.shape

(3, 2)

In [7]:
# The total number elements in the array.
data.size

6

In [9]:
# Number of bytes used to store the data.
data.nbytes 

48

In [12]:
# The data type of the elements in the array.
data.dtype

dtype('int64')

In [14]:
data1 = np.array([1,2,3], dtype=np.int)

In [15]:
data1.dtype

dtype('int64')

In [16]:
data1.nbytes

24

In [17]:
data_complex = np.array([1, 2, 3], dtype=np.complex)

In [18]:
data_complex.nbytes

48

In [19]:
d1 = np.array([1, 2, 3], dtype=float)

In [20]:
d2 = np.array([1, 2, 3], dtype=complex)

In [21]:
d2.dtype

dtype('complex128')

In [22]:
(d1 + d2).dtype

dtype('complex128')

In [23]:
d1.imag

array([0., 0., 0.])

In [24]:
d1.real

array([1., 2., 3.])

In [25]:
np.transpose(data)

array([[2, 3, 5],
       [2, 4, 6]])

In [27]:
data.reshape((2, 3))

array([[2, 2, 3],
       [4, 5, 6]])

In [28]:
x = np.ones((1, 2, 3))

In [29]:
x.shape

(1, 2, 3)

In [30]:
x.size

6

In [35]:
data3 = np.array([[[1,2,3],[4,5,6]]])

In [36]:
np.transpose(data3, (1,0,2))

array([[[1, 2, 3]],

       [[4, 5, 6]]])

In [38]:
np.zeros((1,5))

array([[0., 0., 0., 0., 0.]])

In [39]:
np.ones((3,2,1))

array([[[1.],
        [1.]],

       [[1.],
        [1.]],

       [[1.],
        [1.]]])

In [40]:
# Creates a diagonal array with specified values along the diagonal and zeros elsewhere. 
np.diag((3,2))

array([[3, 0],
       [0, 2]])

In [43]:
np.diag((1,3,4))

array([[1, 0, 0],
       [0, 3, 0],
       [0, 0, 4]])

In [44]:
x1 = 5.4 * np.ones(10)

In [45]:
x2 = np.full(10, 5.4)

In [46]:
x1

array([5.4, 5.4, 5.4, 5.4, 5.4, 5.4, 5.4, 5.4, 5.4, 5.4])

In [47]:
x2

array([5.4, 5.4, 5.4, 5.4, 5.4, 5.4, 5.4, 5.4, 5.4, 5.4])

In [48]:
x1 = np.empty(5)