In [1]:
import numpy as np

In [2]:
data = np.random.randn(2, 3)

In [3]:
data

array([[-1.58072934,  0.14107625, -1.71633907],
       [ 0.0468985 , -0.20200655,  1.24853777]])

In [4]:
data * 10

array([[-15.80729336,   1.41076248, -17.16339069],
       [  0.46898498,  -2.02006548,  12.48537773]])

In [5]:
data + data

array([[-3.16145867,  0.2821525 , -3.43267814],
       [ 0.093797  , -0.4040131 ,  2.49707555]])

In [6]:
data.shape

(2, 3)

In [7]:
data.dtype

dtype('float64')

In [8]:
data1 = [6, 7.5, 8, 0, 1]

In [9]:
arr1 = np.array(data1)

In [10]:
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [11]:
data2 = [[1,2,3,4], [5,6,7,8]]

In [12]:
arr2 = np.array(data2)

In [13]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [14]:
arr1.ndim

1

In [15]:
arr2.ndim

2

In [16]:
arr2.shape

(2, 4)

In [17]:
arr1.dtype

dtype('float64')

In [18]:
arr2.dtype

dtype('int64')

In [19]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [20]:
np.zeros((3, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [21]:
np.empty((2,3,2))

array([[[2.00000000e+000, 2.00000000e+000],
        [2.96439388e-323, 0.00000000e+000],
        [2.12199579e-314, 3.76231868e+174]],

       [[6.50935234e-091, 6.49265498e+169],
        [6.55141380e-043, 1.71830041e+185],
        [3.99910963e+252, 8.34404860e-309]]])

In [22]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [23]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [24]:
np.ones_like(10)

array(1)

In [25]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [26]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [27]:
np.eye(10, dtype=np.float64)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [28]:
arr = np.array([1, 2, 3, 4, 5])

In [29]:
arr.dtype

dtype('int64')

In [30]:
float_arr = arr.astype(np.float64)

In [31]:
float_arr.dtype

dtype('float64')

In [32]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])

In [33]:
arr

array([ 3.7, -1.2, -2.6,  0.5, 12.9, 10.1])

In [34]:
int_arr = arr.astype(np.int64)

In [35]:
int_arr

array([ 3, -1, -2,  0, 12, 10])

In [36]:
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype=np.string_)

In [37]:
numeric_strings.astype(float)

array([ 1.25, -9.6 , 42.  ])

In [38]:
int_array = np.arange(10)

In [39]:
calibers = np.array([.22, .270, .357, .380, .44, .50], dtype=np.float64)

In [40]:
int_array.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [41]:
empty_uint32 = np.empty(8, dtype='u4')

In [42]:
empty_uint32

array([         0, 1075314688,          0, 1075707904,          0,
       1075838976,          0, 1072693248], dtype=uint32)

In [43]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])

In [44]:
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [45]:
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [46]:
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [47]:
1 / arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [48]:
arr ** 0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [49]:
 arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])

In [50]:
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [51]:
arr2 > arr

array([[False,  True, False],
       [ True, False,  True]])

In [52]:
arr = np.arange(10)

In [53]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [54]:
arr[5]

5

In [55]:
arr[5:8]

array([5, 6, 7])

In [56]:
arr[5:8] = 12

In [57]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [58]:
arr_slice = arr[5:8]

In [59]:
arr_slice

array([12, 12, 12])

In [60]:
arr_slice[1] = 12345

In [61]:
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [62]:
 arr_slice[:] = 64

In [63]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [64]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [65]:
arr2d[2]

array([7, 8, 9])

In [66]:
arr2d[0][2]

3

In [67]:
arr2d[0, 2]

3

In [68]:
 arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

In [69]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [70]:
 arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [71]:
old_values = arr3d[0].copy()

In [72]:
arr3d[0] = 42

In [73]:
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [74]:
old_values

array([[1, 2, 3],
       [4, 5, 6]])

In [75]:
arr3d[0] = old_values

In [76]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [77]:
arr3d[1, 0]

array([7, 8, 9])

In [78]:
 x = arr3d[1]

In [79]:
x

array([[ 7,  8,  9],
       [10, 11, 12]])

In [80]:
x[0]

array([7, 8, 9])

In [81]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [82]:
arr[1:6]

array([ 1,  2,  3,  4, 64])

In [83]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [84]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [85]:
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [86]:
arr2d[1, :2]

array([4, 5])

In [87]:
arr2d[:2, 2]

array([3, 6])

In [88]:
 arr2d[:, :1]

array([[1],
       [4],
       [7]])

In [89]:
arr2d[:2, 1:] = 0

In [90]:
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

In [91]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

In [92]:
data = np.random.randn(7, 4)

In [93]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [94]:
data

array([[ 1.83151536,  0.1532781 , -1.48357862, -0.31347954],
       [ 1.52369777,  0.42053437, -1.02696606,  1.11993266],
       [ 0.67664623, -0.7910969 , -0.48663197,  1.89134244],
       [ 0.17955734,  0.11083321, -0.39997671,  1.1203679 ],
       [ 0.87376825, -1.41412251, -1.75049485,  1.32516794],
       [-1.50184013,  0.99162222,  1.45174597, -0.1756949 ],
       [-0.5692627 ,  0.4490644 ,  0.72440493,  0.87383514]])

In [95]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [96]:
data[names == 'Bob']

array([[ 1.83151536,  0.1532781 , -1.48357862, -0.31347954],
       [ 0.17955734,  0.11083321, -0.39997671,  1.1203679 ]])

In [97]:
data[names == 'Bob', 2:]

array([[-1.48357862, -0.31347954],
       [-0.39997671,  1.1203679 ]])

In [98]:
 data[names == 'Bob', 3]

array([-0.31347954,  1.1203679 ])

In [99]:
names != 'Bob'

array([False,  True,  True, False,  True,  True,  True])

In [100]:
data[~(names == 'Bob')]

array([[ 1.52369777,  0.42053437, -1.02696606,  1.11993266],
       [ 0.67664623, -0.7910969 , -0.48663197,  1.89134244],
       [ 0.87376825, -1.41412251, -1.75049485,  1.32516794],
       [-1.50184013,  0.99162222,  1.45174597, -0.1756949 ],
       [-0.5692627 ,  0.4490644 ,  0.72440493,  0.87383514]])

In [101]:
cond = names == 'Bob'

In [102]:
 data[~cond]

array([[ 1.52369777,  0.42053437, -1.02696606,  1.11993266],
       [ 0.67664623, -0.7910969 , -0.48663197,  1.89134244],
       [ 0.87376825, -1.41412251, -1.75049485,  1.32516794],
       [-1.50184013,  0.99162222,  1.45174597, -0.1756949 ],
       [-0.5692627 ,  0.4490644 ,  0.72440493,  0.87383514]])

In [103]:
mask = (names == 'Bob') | (names == 'Will')

In [104]:
mask

array([ True, False,  True,  True,  True, False, False])

In [105]:
data[mask]

array([[ 1.83151536,  0.1532781 , -1.48357862, -0.31347954],
       [ 0.67664623, -0.7910969 , -0.48663197,  1.89134244],
       [ 0.17955734,  0.11083321, -0.39997671,  1.1203679 ],
       [ 0.87376825, -1.41412251, -1.75049485,  1.32516794]])

In [106]:
data[data < 0] = 0

In [107]:
data

array([[1.83151536, 0.1532781 , 0.        , 0.        ],
       [1.52369777, 0.42053437, 0.        , 1.11993266],
       [0.67664623, 0.        , 0.        , 1.89134244],
       [0.17955734, 0.11083321, 0.        , 1.1203679 ],
       [0.87376825, 0.        , 0.        , 1.32516794],
       [0.        , 0.99162222, 1.45174597, 0.        ],
       [0.        , 0.4490644 , 0.72440493, 0.87383514]])

In [108]:
data[names != 'Joe'] = 7

In [109]:
data

array([[7.        , 7.        , 7.        , 7.        ],
       [1.52369777, 0.42053437, 0.        , 1.11993266],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [0.        , 0.99162222, 1.45174597, 0.        ],
       [0.        , 0.4490644 , 0.72440493, 0.87383514]])

In [111]:
arr = np.empty((8, 4))

In [112]:
for i in range(8):
    arr[i] = i

In [113]:
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [114]:
arr[[4, 3, 0, 6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [115]:
 arr[[-3, -5, -7]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

In [116]:
arr = np.arange(32).reshape((8, 4))

In [117]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [118]:
arr[[1, 5, 7, 2], [0, 3, 1, 2]]

array([ 4, 23, 29, 10])

In [119]:
arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

In [120]:
arr = np.arange(15).reshape((3, 5))

In [121]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [122]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [123]:
arr = np.random.randn(6, 3)

In [124]:
arr

array([[-0.73469947, -0.19007003, -0.57934817],
       [-0.9532043 , -0.03056918, -1.64090528],
       [-0.68353148,  0.08971425, -1.90680769],
       [ 0.20921084, -0.62136406, -2.00011387],
       [-0.53370444, -0.45185674,  0.80543988],
       [-0.29284427, -0.81953148,  0.81008137]])

In [125]:
np.dot(arr.T, arr)

array([[ 2.32996442,  0.45861746,  2.20758784],
       [ 0.45861746,  1.30700938,  0.20417827],
       [ 2.20758784,  0.20417827, 11.96955075]])

In [126]:
arr = np.arange(16).reshape((2, 2, 4))

In [127]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [128]:
arr.transpose((1, 0, 2))

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])