In [2]:
import numpy as np

In [3]:
arr = np.arange(10)

In [4]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [6]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [7]:
x = np.random.randn(8)

In [8]:
 y = np.random.randn(8)

In [9]:
x

array([-0.28730785,  0.19638564,  0.33660121,  0.51470935,  0.47132729,
        0.3534613 ,  0.67047973, -0.00976483])

In [10]:
y

array([ 1.73781126,  0.1176813 ,  1.33946532, -0.21839332, -0.56733749,
       -1.52732155,  0.6197683 ,  1.43857566])

In [12]:
np.maximum(x, y)

array([1.73781126, 0.19638564, 1.33946532, 0.51470935, 0.47132729,
       0.3534613 , 0.67047973, 1.43857566])

In [14]:
arr = np.random.randn(7) * 5

In [25]:
arr

array([1.87161172,        nan,        nan,        nan,        nan,
              nan,        nan])

In [26]:
remainder, whole_part = np.modf(arr)

In [27]:
remainder

array([0.87161172,        nan,        nan,        nan,        nan,
              nan,        nan])

In [28]:
whole_part

array([ 1., nan, nan, nan, nan, nan, nan])

In [29]:
np.sqrt(arr)

array([1.36806861,        nan,        nan,        nan,        nan,
              nan,        nan])

In [30]:
np.sqrt(arr, arr)

array([1.36806861,        nan,        nan,        nan,        nan,
              nan,        nan])

In [31]:
np.square(arr)

array([1.87161172,        nan,        nan,        nan,        nan,
              nan,        nan])

In [32]:
arr ** 2

array([1.87161172,        nan,        nan,        nan,        nan,
              nan,        nan])

In [33]:
arr

array([1.36806861,        nan,        nan,        nan,        nan,
              nan,        nan])

In [34]:
arr = np.random.randn(7) * 5

In [35]:
arr

array([10.78774062, -7.93034951, -1.79406117,  0.4682685 , -2.05081321,
       -2.60335112, -6.4008629 ])

In [36]:
np.power(arr, 2)

array([116.37534775,  62.89044332,   3.21865547,   0.21927538,
         4.20583481,   6.77743705,  40.97104583])

In [37]:
arr * arr

array([116.37534775,  62.89044332,   3.21865547,   0.21927538,
         4.20583481,   6.77743705,  40.97104583])

In [38]:
arr ** 2

array([116.37534775,  62.89044332,   3.21865547,   0.21927538,
         4.20583481,   6.77743705,  40.97104583])

In [39]:
np.square(arr)

array([116.37534775,  62.89044332,   3.21865547,   0.21927538,
         4.20583481,   6.77743705,  40.97104583])