In [1]:
import numpy as np

In [3]:
a = np.arange(5)
a.dtype

(5,)

In [4]:
a

array([0, 1, 2, 3, 4])

In [5]:
a.shape

(5,)

In [7]:
m = np.array([np.arange(2), np.arange(2)])
m

array([[0, 1],
       [0, 1]])

In [8]:
m.shape

(2, 2)

In [9]:
m[0, 0]

0

In [10]:
m[1,1]

1

In [11]:
m.dtype.itemsize

8

In [13]:
np.arange(7, dtype='f')

array([0., 1., 2., 3., 4., 5., 6.], dtype=float32)

In [14]:
np.arange(7, dtype='D')

array([0.+0.j, 1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j, 5.+0.j, 6.+0.j])

In [15]:
np.sctypeDict.keys()

dict_keys(['?', 0, 'byte', 'b', 1, 'ubyte', 'B', 2, 'short', 'h', 3, 'ushort', 'H', 4, 'i', 5, 'uint', 'I', 6, 'intp', 'p', 7, 'uintp', 'P', 8, 'long', 'l', 'L', 'longlong', 'q', 9, 'ulonglong', 'Q', 10, 'half', 'e', 23, 'f', 11, 'double', 'd', 12, 'longdouble', 'g', 13, 'cfloat', 'F', 14, 'cdouble', 'D', 15, 'clongdouble', 'G', 16, 'O', 17, 'S', 18, 'unicode', 'U', 19, 'void', 'V', 20, 'M', 21, 'm', 22, 'bool8', 'Bool', 'b1', 'float16', 'Float16', 'f2', 'float32', 'Float32', 'f4', 'float64', 'Float64', 'f8', 'float128', 'Float128', 'f16', 'complex64', 'Complex32', 'c8', 'complex128', 'Complex64', 'c16', 'complex256', 'Complex128', 'c32', 'object0', 'Object0', 'bytes0', 'Bytes0', 'str0', 'Str0', 'void0', 'Void0', 'datetime64', 'Datetime64', 'M8', 'timedelta64', 'Timedelta64', 'm8', 'int64', 'Int64', 'i8', 'uint64', 'UInt64', 'u8', 'int32', 'Int32', 'i4', 'uint32', 'UInt32', 'u4', 'int16', 'Int16', 'i2', 'uint16', 'UInt16', 'u2', 'int8', 'Int8', 'i1', 'uint8', 'UInt8', 'u1', 'complex_',

In [22]:
np.dtype('float64').char

## np.dtype('Flaot64') will get 'DeprecationWarning: Numeric-style type codes are deprecated and will result in an error in the future.'

'd'

In [26]:
t = np.dtype([('name', np.str_, 40), ('numitems', np.int32), ('price', np.float32)])
t['name']

dtype('<U40')

In [30]:
itemz =  np.array([('Meaning of life DVD', 42.2, 3.13), ('Butter', 13, 2.72)], dtype=t)
itemz

array([('Meaning of life DVD', 42, 3.13), ('Butter', 13, 2.72)],
      dtype=[('name', '<U40'), ('numitems', '<i4'), ('price', '<f4')])

In [31]:
a = np.arange(9)
a[3:7]

array([3, 4, 5, 6])

In [32]:
a[:7:2]

array([0, 2, 4, 6])

In [33]:
 a[::-1]

array([8, 7, 6, 5, 4, 3, 2, 1, 0])

In [35]:
b = np.arange(24).reshape(2,3,4)
b.shape

(2, 3, 4)

In [36]:
b

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [37]:
b[0, 0, 0]

0

In [38]:
b[1,2,3]

23

In [39]:
b[:,0,0]

array([ 0, 12])

In [40]:
 b[0,1,::2]

array([4, 6])

In [41]:
b[...,1]

array([[ 1,  5,  9],
       [13, 17, 21]])

In [42]:
 b[0,:,1]

array([1, 5, 9])

In [43]:
b[0,:,-1]

array([ 3,  7, 11])

In [44]:
b[0,::-1, -1]

array([11,  7,  3])

In [45]:
b[0,::2,-1]

array([ 3, 11])

In [46]:
b.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [47]:
b.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [48]:
c = b.ravel() # ravel() might return a view of the array, change the view will change the original array
c[12] = 100
b

array([[[  0,   1,   2,   3],
        [  4,   5,   6,   7],
        [  8,   9,  10,  11]],

       [[100,  13,  14,  15],
        [ 16,  17,  18,  19],
        [ 20,  21,  22,  23]]])

In [49]:
d = b.flatten() # flatten() always allocates new memory, change the it won't change the original array
d[12] = 100
b

array([[[  0,   1,   2,   3],
        [  4,   5,   6,   7],
        [  8,   9,  10,  11]],

       [[100,  13,  14,  15],
        [ 16,  17,  18,  19],
        [ 20,  21,  22,  23]]])

In [50]:
b.reshape(4,6)

array([[  0,   1,   2,   3,   4,   5],
       [  6,   7,   8,   9,  10,  11],
       [100,  13,  14,  15,  16,  17],
       [ 18,  19,  20,  21,  22,  23]])

In [51]:
b.shape = (6,4)
b

array([[  0,   1,   2,   3],
       [  4,   5,   6,   7],
       [  8,   9,  10,  11],
       [100,  13,  14,  15],
       [ 16,  17,  18,  19],
       [ 20,  21,  22,  23]])

In [52]:
b.transpose()

array([[  0,   4,   8, 100,  16,  20],
       [  1,   5,   9,  13,  17,  21],
       [  2,   6,  10,  14,  18,  22],
       [  3,   7,  11,  15,  19,  23]])

In [54]:
b.resize((2,12))
b

array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11],
       [100,  13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23]])

In [55]:
b.reshape(4,6) # reshape won't change the original array but create a new one
b

array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11],
       [100,  13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23]])

In [56]:
a = np.arange(9).reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [61]:
b = a * 2
b

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [63]:
np.hstack((a, b))

array([[ 0,  1,  2,  0,  2,  4],
       [ 3,  4,  5,  6,  8, 10],
       [ 6,  7,  8, 12, 14, 16]])

In [64]:
np.vstack((a, b))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [65]:
np.dstack((a, b))

array([[[ 0,  0],
        [ 1,  2],
        [ 2,  4]],

       [[ 3,  6],
        [ 4,  8],
        [ 5, 10]],

       [[ 6, 12],
        [ 7, 14],
        [ 8, 16]]])

In [67]:
oned = np.arange(2)
twice_oned = 2 * oned

In [68]:
np.column_stack((oned, twice_oned))

array([[0, 0],
       [1, 2]])

In [69]:
np.column_stack((a, b))

array([[ 0,  1,  2,  0,  2,  4],
       [ 3,  4,  5,  6,  8, 10],
       [ 6,  7,  8, 12, 14, 16]])

In [70]:
np.row_stack((oned, twice_oned))

array([[0, 1],
       [0, 2]])

In [71]:
np.row_stack((a, b))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [72]:
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [74]:
np.hsplit(a, 3)

[array([[0],
        [3],
        [6]]), array([[1],
        [4],
        [7]]), array([[2],
        [5],
        [8]])]

In [75]:
np.split(a, 3, axis = 1)

[array([[0],
        [3],
        [6]]), array([[1],
        [4],
        [7]]), array([[2],
        [5],
        [8]])]

In [76]:
np.vsplit(a, 3)

[array([[0, 1, 2]]), array([[3, 4, 5]]), array([[6, 7, 8]])]

In [79]:
np.split(a, 3, axis = 0)

[array([[0, 1, 2]]), array([[3, 4, 5]]), array([[6, 7, 8]])]

In [80]:
c = np.arange(27).reshape(3, 3, 3)
c

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [81]:
np.dsplit(c, 3)

[array([[[ 0],
         [ 3],
         [ 6]],
 
        [[ 9],
         [12],
         [15]],
 
        [[18],
         [21],
         [24]]]), array([[[ 1],
         [ 4],
         [ 7]],
 
        [[10],
         [13],
         [16]],
 
        [[19],
         [22],
         [25]]]), array([[[ 2],
         [ 5],
         [ 8]],
 
        [[11],
         [14],
         [17]],
 
        [[20],
         [23],
         [26]]])]

In [82]:
b

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [83]:
b.ndim

2

In [84]:
b.size

9

In [85]:
b.itemsize

8

In [86]:
b.nbytes

72

In [87]:
b.T

array([[ 0,  6, 12],
       [ 2,  8, 14],
       [ 4, 10, 16]])

In [89]:
b = np.array([1.j + 1, 2.j + 3])

In [90]:
b.real

array([1., 3.])

In [92]:
b.imag

array([1., 2.])

In [93]:
b.dtype

dtype('complex128')

In [96]:
b.flat[1]

(3+2j)

In [97]:
b.tolist()

[(1+1j), (3+2j)]

In [ ]:
b.astyp