In [70]:
import numpy as np
i2 = np.eye(2)
i2

array([[1., 0.],
       [0., 1.]])

In [71]:
np.savetxt("eye.txt", i2)

In [72]:
c,v = np.loadtxt('data.csv', delimiter=',', usecols=(6,7), unpack=True)

In [73]:
c

array([336.1 , 339.32, 345.03, 344.32, 343.44, 346.5 , 351.88, 355.2 ,
       358.16, 354.54, 356.85, 359.18, 359.9 , 363.13, 358.3 , 350.56,
       338.61, 342.62, 342.88, 348.16, 353.21, 349.31, 352.12, 359.56,
       360.  , 355.36, 355.76, 352.47, 346.67, 351.99])

In [74]:
v

array([21144800., 13473000., 15236800.,  9242600., 14064100., 11494200.,
       17322100., 13608500., 17240800., 33162400., 13127500., 11086200.,
       10149000., 17184100., 18949000., 29144500., 31162200., 23994700.,
       17853500., 13572000., 14395400., 16290300., 21521000., 17885200.,
       16188000., 19504300., 12718000., 16192700., 18138800., 16824200.])

In [75]:
vwap= np.average(c, weights=v) # This is same as np.sum(c * v) / np.sum(v)
vwap

350.5895493532009

In [76]:
ca= np.average(c) # Same as np.mean(c) and same as  np.average(c, weights=np.ones(len(c)))
ca

351.0376666666667

In [77]:
t = np.average(c, weights=np.arange(len(c)))
t

352.4283218390804

In [78]:
h, l = np.loadtxt('data.csv', delimiter=',', usecols=(4,5), unpack=True)

In [79]:
np.max(h)

364.9

In [80]:
np.min(l)

333.53

In [81]:
np.ptp(h) # same as np.max(h) - np.min(h)

24.859999999999957

In [82]:
np.max(h) - np.min(h)

24.859999999999957

In [83]:
np.median(c)

352.055

In [84]:
sorted_close = np.msort(c)

In [85]:
i_sorted_close = len(c)

In [86]:
mi = i_sorted_close // 2 
if i_sorted_close % 2 == 0:
    m = (sorted_close[mi] + sorted_close[mi - 1]) /2
else:
    m = sorted_close[mi]
m

352.055

In [87]:
np.var(c)

50.126517888888884

In [88]:
np.mean((c - c.mean()) ** 2)

50.126517888888884

In [89]:
returns = np.diff(c) / c[:-1]
returns

array([ 0.00958048,  0.01682777, -0.00205779, -0.00255576,  0.00890985,
        0.0155267 ,  0.00943503,  0.00833333, -0.01010721,  0.00651548,
        0.00652935,  0.00200457,  0.00897472, -0.01330102, -0.02160201,
       -0.03408832,  0.01184253,  0.00075886,  0.01539897,  0.01450483,
       -0.01104159,  0.00804443,  0.02112916,  0.00122372, -0.01288889,
        0.00112562, -0.00924781, -0.0164553 ,  0.01534601])

In [90]:
logreturns = np.diff(np.log(c))
logreturns

array([ 0.00953488,  0.01668775, -0.00205991, -0.00255903,  0.00887039,
        0.01540739,  0.0093908 ,  0.0082988 , -0.01015864,  0.00649435,
        0.00650813,  0.00200256,  0.00893468, -0.01339027, -0.02183875,
       -0.03468287,  0.01177296,  0.00075857,  0.01528161,  0.01440064,
       -0.011103  ,  0.00801225,  0.02090904,  0.00122297, -0.01297267,
        0.00112499, -0.00929083, -0.01659219,  0.01522945])

In [91]:
postindices = np.where(returns > 0)
postindices

(array([ 0,  1,  4,  5,  6,  7,  9, 10, 11, 12, 16, 17, 18, 19, 21, 22, 23,
        25, 28], dtype=int64),)