In [2]:
import numpy as np
i2 = np.eye(2)

In [3]:
i2

array([[1., 0.],
       [0., 1.]])

In [4]:
np.savetxt("eye.txt", i2)

In [5]:
c,v = np.loadtxt('data.csv', delimiter=',', usecols=(6,7), unpack=True)

In [6]:
c

array([336.1 , 339.32, 345.03, 344.32, 343.44, 346.5 , 351.88, 355.2 ,
       358.16, 354.54, 356.85, 359.18, 359.9 , 363.13, 358.3 , 350.56,
       338.61, 342.62, 342.88, 348.16, 353.21, 349.31, 352.12, 359.56,
       360.  , 355.36, 355.76, 352.47, 346.67, 351.99])

In [7]:
v

array([21144800., 13473000., 15236800.,  9242600., 14064100., 11494200.,
       17322100., 13608500., 17240800., 33162400., 13127500., 11086200.,
       10149000., 17184100., 18949000., 29144500., 31162200., 23994700.,
       17853500., 13572000., 14395400., 16290300., 21521000., 17885200.,
       16188000., 19504300., 12718000., 16192700., 18138800., 16824200.])

In [15]:
vwap= np.average(c, weights=v) # This is same as np.sum(c * v) / np.sum(v)

In [16]:
vwap

350.5895493532009

In [17]:
ca= np.average(c) # Same as np.mean(c) and same as  np.average(c, weights=np.ones(len(c)))

In [18]:
ca

351.0376666666667

In [25]:
t = np.average(c, weights=np.arange(len(c)))

In [26]:
t

352.4283218390804

In [27]:
h, l = np.loadtxt('data.csv', delimiter=',', usecols=(4,5), unpack=True)

In [28]:
np.max(h)

364.9

In [29]:
np.min(l)

333.53

In [30]:
np.ptp(h) # same as np.max(h) - np.min(h)

24.859999999999957

In [31]:
np.max(h) - np.min(h)

24.859999999999957

In [32]:
np.median(c)

352.055

In [33]:
sorted_close = np.msort(c)

In [38]:
i_sorted_close = len(c)

352.12

In [42]:
mi = i_sorted_close // 2 
if i_sorted_close % 2 == 0:
    m = (sorted_close[mi] + sorted_close[mi - 1]) /2
else:
    m = sorted_close[mi]

In [44]:
m

352.055

In [45]:
np.var(c)

50.126517888888884

In [62]:
np.mean((c - c.mean()) ** 2)

50.126517888888884