In [26]:
import numpy as np
i2 = np.eye(2)
i2

array([[1., 0.],
       [0., 1.]])

In [27]:
np.savetxt("eye.txt", i2)

In [28]:
c,v = np.loadtxt('data.csv', delimiter=',', usecols=(6,7), unpack=True)

In [29]:
c

array([336.1 , 339.32, 345.03, 344.32, 343.44, 346.5 , 351.88, 355.2 ,
       358.16, 354.54, 356.85, 359.18, 359.9 , 363.13, 358.3 , 350.56,
       338.61, 342.62, 342.88, 348.16, 353.21, 349.31, 352.12, 359.56,
       360.  , 355.36, 355.76, 352.47, 346.67, 351.99])

In [30]:
v

array([21144800., 13473000., 15236800.,  9242600., 14064100., 11494200.,
       17322100., 13608500., 17240800., 33162400., 13127500., 11086200.,
       10149000., 17184100., 18949000., 29144500., 31162200., 23994700.,
       17853500., 13572000., 14395400., 16290300., 21521000., 17885200.,
       16188000., 19504300., 12718000., 16192700., 18138800., 16824200.])

In [31]:
vwap= np.average(c, weights=v) # This is same as np.sum(c * v) / np.sum(v)
vwap

350.5895493532009

In [32]:
ca= np.average(c) # Same as np.mean(c) and same as  np.average(c, weights=np.ones(len(c)))
ca

351.0376666666667

In [33]:
t = np.average(c, weights=np.arange(len(c)))
t

352.4283218390804

In [34]:
h, l = np.loadtxt('data.csv', delimiter=',', usecols=(4,5), unpack=True)

In [35]:
np.max(h)

364.9

In [36]:
np.min(l)

333.53

In [37]:
np.ptp(h) # same as np.max(h) - np.min(h)

24.859999999999957

In [38]:
np.max(h) - np.min(h)

24.859999999999957

In [39]:
np.median(c)

352.055

In [40]:
sorted_close = np.msort(c)

In [41]:
i_sorted_close = len(c)

In [42]:
mi = i_sorted_close // 2 
if i_sorted_close % 2 == 0:
    m = (sorted_close[mi] + sorted_close[mi - 1]) /2
else:
    m = sorted_close[mi]
m

352.055

In [43]:
np.var(c)

50.126517888888884

In [44]:
np.mean((c - c.mean()) ** 2)

50.126517888888884

In [45]:
returns = np.diff(c) / c[:-1]
returns

array([ 0.00958048,  0.01682777, -0.00205779, -0.00255576,  0.00890985,
        0.0155267 ,  0.00943503,  0.00833333, -0.01010721,  0.00651548,
        0.00652935,  0.00200457,  0.00897472, -0.01330102, -0.02160201,
       -0.03408832,  0.01184253,  0.00075886,  0.01539897,  0.01450483,
       -0.01104159,  0.00804443,  0.02112916,  0.00122372, -0.01288889,
        0.00112562, -0.00924781, -0.0164553 ,  0.01534601])

In [46]:
logreturns = np.diff(np.log(c))
logreturns

array([ 0.00953488,  0.01668775, -0.00205991, -0.00255903,  0.00887039,
        0.01540739,  0.0093908 ,  0.0082988 , -0.01015864,  0.00649435,
        0.00650813,  0.00200256,  0.00893468, -0.01339027, -0.02183875,
       -0.03468287,  0.01177296,  0.00075857,  0.01528161,  0.01440064,
       -0.011103  ,  0.00801225,  0.02090904,  0.00122297, -0.01297267,
        0.00112499, -0.00929083, -0.01659219,  0.01522945])

In [47]:
postindices = np.where(returns > 0)
postindices

(array([ 0,  1,  4,  5,  6,  7,  9, 10, 11, 12, 16, 17, 18, 19, 21, 22, 23,
        25, 28]),)

In [50]:
1 - logreturns

array([0.99046512, 0.98331225, 1.00205991, 1.00255903, 0.99112961,
       0.98459261, 0.9906092 , 0.9917012 , 1.01015864, 0.99350565,
       0.99349187, 0.99799744, 0.99106532, 1.01339027, 1.02183875,
       1.03468287, 0.98822704, 0.99924143, 0.98471839, 0.98559936,
       1.011103  , 0.99198775, 0.97909096, 0.99877703, 1.01297267,
       0.99887501, 1.00929083, 1.01659219, 0.98477055])

In [51]:
from scipy.stats import gmean
gmean(1 - logreturns)

0.9983234381297623

In [54]:
annual_volatility = np.std(logreturns)/np.mean(logreturns)
annual_volatility = annual_volatility / np.sqrt(1./252.)
print(annual_volatility)

129.27478991115132


In [66]:
import datetime
def datestr2num(s):
    try:
        return datetime.datetime.strptime(s.decode("utf-8"), "%d-%m-%Y").date().weekday()
    except:
        return datetime.datetime.strptime(s.decode("utf-8"), "%d/%m/%Y").date().weekday()
dates, close=np.loadtxt('data.csv', delimiter=',',  converters={1: datestr2num}, usecols=(1,6), unpack=True)
print(dates)

[4. 0. 1. 2. 3. 4. 0. 1. 2. 3. 4. 0. 1. 2. 3. 4. 1. 2. 3. 4. 0. 1. 2. 3.
 4. 0. 1. 2. 3. 4.]


In [67]:
averages = np.zeros(5)
for i in range(5):
    indices = np.where(dates == i)
    prices = np.take(close, indices)
    avg = np.mean(prices)
    print("Day", i, "prices", prices, "Average", avg)
    averages[i] = avg

Day 0 prices [[339.32 351.88 359.18 353.21 355.36]] Average 351.7900000000001
Day 1 prices [[345.03 355.2  359.9  338.61 349.31 355.76]] Average 350.63500000000005
Day 2 prices [[344.32 358.16 363.13 342.62 352.12 352.47]] Average 352.1366666666666
Day 3 prices [[343.44 354.54 358.3  342.88 359.56 346.67]] Average 350.8983333333333
Day 4 prices [[336.1  346.5  356.85 350.56 348.16 360.   351.99]] Average 350.0228571428571


In [90]:
# We can do the samething with pandas
dc = np.hstack((dates.reshape(len(dates), 1), close.reshape(len(close), 1)))
import pandas as pd
ds = pd.DataFrame(data=dc)
ds.groupby(0)[1].mean()

0
0.0    351.790000
1.0    350.635000
2.0    352.136667
3.0    350.898333
4.0    350.022857
Name: 1, dtype: float64